# Here are 30 random strings, generated by a crazy algorithm, for Windows 95!

import random

# Define a list of valid years (from 1995 to 2003)
valid_years = [str(year)[-2:] for year in range(1995, 2004)]

# Define a list of valid day numbers (from 1 to 366)
valid_days = [str(day).zfill(3) for day in range(1, 367)]

# Generate 30 random strings
for i in range(30):
    # Choose a random year and day
    year = random.choice(valid_years)
    day = random.choice(valid_days)
    
    # Choose a random 7-digit number that sums to a multiple of 7
    nnnnnnn = random.randint(0, 9999999)
    nnnnnnn += (7 - (nnnnnnn % 7)) % 7  # Round up to the nearest multiple of 7
    nnnnnnn = str(nnnnnnn).zfill(7)
    
    # Generate a random string of numbers for the final segment
    zzzzz = ''.join([str(random.randint(0, 9)) for _ in range(5)])
    
    # Combine the parts into the final string
    final_string = f"{day}{year}-OEM-{nnnnnnn}-{zzzzz}"
    
    # Print the final string
    print(final_string)
